PROJECT_ID="liquid-braid-400023"

DOCKER_ENDPOINT="$ZONE-docker.pkg.dev"
DOCKER_REPO="timaeus-$ZONE"
DOCKER_IMAGE_NAME="forms"
DOCKER_TAG="latest"
DOCKER_PATH="$DOCKER_ENDPOINT/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IMAGE_NAME:$DOCKER_TAG"

docker build -t $DOCKER_IMAGE_NAME .
docker tag $DOCKER_IMAGE_NAME $DOCKER_PATH
docker push $DOCKER_IMAGE_NAME $DOCKER_PATH