name: small-model-sweep
method: grid
command: ["python", "icl/analysis", "sweep"]
project: icl
entity: devinterp
parameters:
  analysis_config:
    parameters:
      elasticity:
        value: 1.
      num_draws:
        value: 100
      lr: 
        value: 0.00001
      num_chains:
        value: 5
      num_repeats:
        value: 5
  task_config: 
    parameters:
      task_size:
        value: 4
      max_examples:
        value: 8
      num_tasks:
        values: [1, 65536, 64, 4, 16384, 16, 4096, 256, 1024]
        # values: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576]
      noise_variance:
        value: 0.125
      embed_size:
        value: 64
      mlp_size:
        value: 64
      num_heads:
        value: 4
      num_layers:
        value: 2
        # values: [1, 2, 4]
      model_seed:
        value: 0
      pretrain_seed:
        value: 1
      true_seed:
        value: 2
      sampling_seed:
        value: 3
  optimizer_config:
    parameters:
      lr:
        value: 0.001
        # values: [0.0003, 0.001, 0.003]
  eval_batch_size:
    value: 2048
